
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo-10-bdd-oo2-2022
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #Generar esquema desde Java hacia la BD
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false #Permite modificar vistar sin reset del servidor   

